import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";
import type { ImpactReceiptRecord } from "./csr-impact-data";

const styles = StyleSheet.create({
  page: {
    paddingTop: 34,
    paddingBottom: 36,
    paddingHorizontal: 36,
    fontSize: 11,
    color: "#333333",
    backgroundColor: "#F8F5EF",
  },
  header: {
    marginBottom: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#D8D3CA",
  },
  brand: {
    fontSize: 10,
    letterSpacing: 2.1,
    color: "#6B8E23",
    marginBottom: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 11,
    color: "#5C564E",
    lineHeight: 1.45,
  },
  grid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 18,
  },
  metricCard: {
    flex: 1,
    padding: 12,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2DDD5",
  },
  metricLabel: {
    fontSize: 9,
    letterSpacing: 1.4,
    color: "#6E655D",
    marginBottom: 6,
    textTransform: "uppercase",
  },
  metricValue: {
    fontSize: 16,
    fontWeight: 700,
    color: "#333333",
  },
  section: {
    marginBottom: 16,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2DDD5",
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#3F51B5",
    marginBottom: 8,
  },
  paragraph: {
    lineHeight: 1.6,
    color: "#44403A",
  },
  listItem: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 6,
  },
  bullet: {
    width: 10,
    color: "#D1603D",
  },
  listText: {
    flex: 1,
    lineHeight: 1.55,
    color: "#44403A",
  },
  footer: {
    marginTop: 10,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#D8D3CA",
    fontSize: 9,
    color: "#7A746D",
    lineHeight: 1.5,
  },
});

function formatCurrency(amount: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function ImpactReceiptDocument({
  receipt,
}: {
  receipt: ImpactReceiptRecord;
}) {
  return (
    <Document title={receipt.receiptNumber}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>RESOURCEMATCH IMPACT RECEIPT</Text>
          <Text style={styles.title}>{receipt.needTitle}</Text>
          <Text style={styles.subtitle}>
            Board-ready summary of funded need, resources deployed, and verified
            community outcome for donor reporting and audit review.
          </Text>
        </View>

        <View style={styles.grid}>
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Receipt Number</Text>
            <Text style={styles.metricValue}>{receipt.receiptNumber}</Text>
          </View>
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Donation Amount</Text>
            <Text style={styles.metricValue}>{formatCurrency(receipt.amount)}</Text>
          </View>
        </View>

        <View style={styles.grid}>
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Donor</Text>
            <Text style={styles.metricValue}>{receipt.donor}</Text>
          </View>
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Location</Text>
            <Text style={styles.metricValue}>{receipt.location}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Verified Outcome</Text>
          <Text style={styles.paragraph}>{receipt.verifiedOutcome}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Resources Deployed</Text>
          {receipt.resourcesDeployed.map((item) => (
            <View key={item} style={styles.listItem}>
              <Text style={styles.bullet}>•</Text>
              <Text style={styles.listText}>{item}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Board Notes</Text>
          {receipt.boardNotes.map((item) => (
            <View key={item} style={styles.listItem}>
              <Text style={styles.bullet}>•</Text>
              <Text style={styles.listText}>{item}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by ResourceMatch on behalf of verified NGO coordination
          teams. This summary is compiled from need records, dispatch evidence,
          volunteer confirmation, and field verification logs.
        </Text>
      </Page>
    </Document>
  );
}
